modLoader="javafml"
loaderVersion="[31,)"

[[mods]]
modId="bleach"
version="1.0.0"
displayName="Bleach"
credits="Created using mod maker MCreator - https://mcreator.net/about"
displayURL="https://mcreator.net"
authors="mart-, MCreator"

[[dependencies.bleach]]
    modId="minecraft"
    mandatory=true
    versionRange="[1.15.2]"
    ordering="NONE"
    side="BOTH"




